// HERE BELOW COULD BE DUPLICATES

const myListVerbs = [
    "to be",
    "to have",
    "to become",
    "can",
    "to be able to",
    "must",
    "to have to",
    "to say",
    "to do",
    "to make",
    "to give",
    "to come",
    "should",
    "to be supposed to",
    "to want",
    "to go",
    "to know",
    "to see",
    "to let",
    "to allow",
    "to stand",
    "to find",
    "to stay",
    "to lie",
    "to be called",
    "to think",
    "to take",
    "to do",
    "may",
    "to be allowed to",
    "to believe",
    "to hold",
    "to name",
    "to call",
    "to like",
    "to show",
    "to lead",
    "to speak",
    "to bring",
    "to live",
    "to drive",
    "to go",
    "to mean",
    "to think",
    "to ask",
    "to know",
    "to apply",
    "to be valid",
    "to put",
    "to place",
    "to play",
    "to work",
    "to need",
    "to follow",
    "to learn",
    "to understand",
    "to set",
    "to put",
    "to receive",
    "to get",
    "to begin",
    "to tell",
    "to try",
    "to attempt",
    "to write",
    "to run",
    "to walk",
    "to eat",
    "to drink",
    "to read",
    "to love",
    "to buy",
    "to search",
    "to look for",
    "to feel",
    "to listen",
    "to meet",
    "to build",
    "to rest",
    "to sleep",
    "to cook",
    "to sell",
    "to end",
    "to explain",
    "to plan",
    "to dance",
    "to fall",
    "to remember",
    "to reach",
    "to laugh",
    "to change",
    "to sit",
    "to carry",
    "to wear",
    "to open",
    "to close",
    "to use",
    "to help",
    "to fetch",
    "to forget",
    "to visit",
    "to travel",
    "to win",
    "to request",
    "to ask",
    "to grow",
    "to stand up",
    "to get up",
    "to offer",
    "to bake",
    "to arrive",
    "to happen",
    "to be missing",
    "to break",
    "to create",
    "to manage",
    "to behave",
    "to work out",
    "to burn",
    "to experience",
    "to consider",
    "to call",
    "to telephone",
    "to mean",
    "to leave",
    "to send",
    "to steal",
    "to transfer",
    "to change",
    "to learn",
    "to find out",
    "to stop",
    "to quit",
    "to open up",
    "to get out",
    "to exit",
    "to invite",
    "to lose",
    "to put on",
    "to get dressed",
    "to turn off",
    "to clean up",
    "to watch",
    "to rest",
    "to pray",
    "to compare",
    "to prevent",
    "to agree",
    "to influence",
    "to hug",
    "to depart",
    "to carry out",
    "to celebrate",
    "to belong",
    "to cancel",
    "to order",
    "to turn back",
    "to suggest",
    "to pick up",
    "to watch",
    "to observe",
    "to listen",
    "to call",
    "to answer",
    "to get in",
    "to get on",
    "to recommend",
    "to undress",
    "to move out",
    "to live",
    "to try",
    "to test",
    "to give",
    "to gift",
    "to practice",
    "to clean",
    "to relax",
    "to report",
    "to notify",
    "to hand in",
    "to check",
    "to test",
    "to decide",
    "to educate",
    "to raise",
    "to fit",
    "to suit",
    "to finish",
    "to complete",
    "to close",
    "to look at",
    "to use",
    "to rinse",
    "to answer",
    "to take care of",
    "to notice",
    "to come back",
    "to prepare",
    "to receive",
    "to promise",
    "to take",
    "to explore",
    "to forget",
    "to cover",
    "to withdraw",
    "to take off",
    "to move in",
    "to implement",
    "to fill out",
    "to collaborate",
    "to return",
    "to switch",
    "to be glad",
    "to take off",
    "to stop",
    "to collect",
    "to enter",
    "to invent",
    "to postpone",
    "to pay attention",
    "to sit down",
    "to find out",
    "to consist",
    "to pass",
    "to enjoy",
    "to hurry",
    "to cut",
    "to check",
    "to set up",
    "to pronounce",
    "to bring with",
    "to set up",
    "to place",
    "to forgive",
    "to offer",
    "to get dressed",
    "to take over",
    "to print",
    "to move",
    "to move in",
    "to move out",
    "to increase",
    "to discover",
    "to calculate",
    "to clarify",
    "to recover",
    "to rent out",
    "to organise",
    "to send",
    "to edit",
    "to process",
    "to accompany",
    "to align",
    "to relay",
    "to emphasise",
    "to remember",
    "to consume",
    "to unpack",
    "to miss",
    "to reduce",
    "to expand",
    "to receive",
    "to dispatch",
    "to send",
    "to act",
    "to behave",
    "to investigate",
    "to take out",
    "to continue",
    "to intend",
    "to plan",
    "to install",
    "to attach",
    "to begin",
    "to start",
    "to occur to",
    "to shop",
    "to inform",
    "to notify",
    "to foresee",
    "to omit",
    "to draw",
    "to continue",
    "to trigger",
    "to activate",
    "to expire",
    "to run out",
    "to represent",
    "to invest",
    "to create",
    "to hide",
    "to observe",
    "to use",
    "to spend",
    "to serve",
    "to use",
    "to delete",
    "to extinguish",
    "to amount to",
    "to adjust",
    "to get to know",
    "to say goodbye",
    "to turn on",
    "to keep free",
    "to secure",
    "to conceal",
    "to keep secret",
    "to arrange",
    "to set up",
    "to fly",
    "to improve",
    "to wait",
    "to ascertain",
    "to complement",
    "to converse",
    "to assure",
    "to insure",
    "to complain",
    "to apply for",
    "to repeat",
    "to spend",
    "to deliver",
    "to remove",
    "to take out",
    "to participate",
    "to prepare",
    "to monitor",
    "to confuse",
    "to calm",
    "to put on",
    "to convince",
    "to add",
    "to summarise",
    "to advise",
    "to arrange",
    "to agree",
    "to issue",
    "to pull",
    "to question",
    "to change",
    "to pay attention to",
    "to undertake",
    "to lend",
    "to borrow",
    "to appear",
    "to cater",
    "to feed",
    "to stand out",
    "to look up",
    "to look at",
    "to watch",
    "to enter",
    "to register",
    "to put down",
    "to bring back",
    "to hire",
    "to set",
    "to adhere",
    "to comply",
    "to lift up",
    "to change",
    "to recognise",
    "to transfer",
    "to conclude",
    "to lock",
    "to support",
    "to send",
    "to repair",
    "to save",
    "to connect",
    "to link",
    "to like",
    "to apply",
    "to use",
    "to request",
    "to turn off",
    "to open",
    "to decide",
    "to concentrate",
    "to deliver",
    "to greet",
    "to calculate",
    "to wake up",
    "to offer",
    "to change",
    "to begin",
    "to look at",
    "to answer",
    "to reply",
    "to work",
    "to look",
    "to appear",
    "to mean",
    "to begin",
    "to start",
    "to get",
    "to order",
    "to visit",
    "to concern",
    "to affect",
    "to offer",
    "to form",
    "to shape",
    "to stay",
    "to need",
    "to bring",
    "to thank",
    "to think",
    "to be allowed to",
    "to develop",
    "to yield",
    "to result in",
    "to recall",
    "to remember",
    "to recognise",
    "to detect",
    "to explain",
    "to reach",
    "to appear",
    "to expect",
    "to await",
    "to eat",
    "to drive",
    "to find",
    "to follow",
    "to ask",
    "to question",
    "to feel",
    "to lead",
    "to give",
    "to go",
    "to belong",
    "to win",
    "to believe",
    "to have",
    "to hold",
    "to act",
    "to trade",
    "to be called",
    "to help",
    "to hear",
    "to listen",
    "to interest",
    "to buy",
    "to know",
    "to come",
    "to be able to",
    "to laugh",
    "to let",
    "to run",
    "to live",
    "to lay",
    "to put down",
    "to learn",
    "to read",
    "to love",
    "to lie down",
    "to mean",
    "to live",
    "to take",
    "to mention",
    "to open",
    "to talk",
    "to travel",
    "to run",
    "to smell",
    "to say",
    "to create",
    "to achieve",
    "to seem",
    "to shine",
    "to sleep",
    "to close",
    "to taste",
    "to write",
    "to see",
    "to be",
    "to send",
    "to sit down",
    "to sing",
    "to sit",
    "ought",
    "to play",
    "to speak",
    "to stand",
    "to put",
    "to study",
    "to search",
    "to look for",
    "to divide",
    "to share",
    "to meet",
    "to encounter",
    "to drink",
    "to do",
    "to connect",
    "to leave",
    "to lose",
    "to understand",
    "to use",
    "to wait",
    "to become",
    "to will",
    "to know",
    "to live",
    "to reside",
    "to want",
    "to count",
    "to show",
    "to demonstrate",
    "to pull",
    "to hand in",
    "to deviate",
    "to retrieve",
    "to activate",
    "to update",
    "to accept",
    "to request",
    "to specify",
    "to create",
    "to register",
    "to accept",
    "to adjust",
    "to call",
    "to appear",
    "to connect",
    "to display",
    "to associate",
    "to stop",
    "to record",
    "to occur",
    "to exhibit",
    "to execute",
    "to design",
    "to deliver",
    "to express",
    "to select",
    "to affect",
    "to authorise",
    "to base",
    "to build",
    "to observe",
    "to edit",
    "to consider",
    "to influence",
    "to impair",
    "to finish",
    "to deal with",
    "to be located",
    "to greet",
    "to keep",
    "to treat",
    "to claim",
    "to maintain",
    "to contain",
    "to contribute",
    "to fight",
    "to strive",
    "to require",
    "to use",
    "to observe",
    "to calculate",
    "to provide",
    "to report",
    "to consider",
    "to be based on",
    "to employ",
    "to accelerate",
    "to limit",
    "to own",
    "to confirm",
    "to exist",
    "to determine",
    "to emphasise",
    "to examine",
    "to run",
    "to move",
    "to prove",
    "to evaluate",
    "to cause",
    "to pay",
    "to source",
    "to ask",
    "to break",
    "to spread",
    "to represent",
    "to deactivate",
    "to cover",
    "to define",
    "to serve",
    "to discuss",
    "to double",
    "to turn",
    "to divide into",
    "to print",
    "to press",
    "to perform",
    "to measure",
    "to echo",
    "to unite",
    "to insert",
    "to enter",
    "to arrive",
    "to agree",
    "to furnish",
    "to include",
    "to deploy",
    "to hire",
    "to receive",
    "to recommend",
    "to end",
    "to remove",
    "to contain",
    "to decide",
    "to apologise",
    "to correspond",
    "to arise",
    "to learn",
    "to record",
    "to take place",
    "to require",
    "to fulfil",
    "to seize",
    "to receive",
    "to impose",
    "to increase",
    "to issue",
    "to permit",
    "to experience",
    "to facilitate",
    "to investigate",
    "to enable",
    "to infer",
    "to replace",
    "to create",
    "to span",
    "to request",
    "to assign",
    "to expand",
    "to tell",
    "to generate",
    "to achieve",
    "to export",
    "to fall",
    "to fell",
    "to catch",
    "to fray",
    "to celebrate",
    "to establish",
    "to realise",
    "to fly",
    "to demand",
    "to promote",
    "to shape",
    "to continue",
    "to free",
    "to make peace",
    "to insert",
    "to function",
    "to guarantee",
    "to command",
    "to arrive",
    "to escort",
    "to apply",
    "to enjoy",
    "to get",
    "to happen",
    "to design",
    "to allow",
    "to grant",
    "to ensure",
    "to resemble",
    "to globalise",
    "to border",
    "to found",
    "to hook",
    "to hang",
    "to marry",
    "to find out",
    "to push",
    "to manufacture",
    "to download",
    "to protrude",
    "to dare",
    "to add",
    "to hope",
    "to fetch",
    "to identify",
    "to import",
    "to inform",
    "to install",
    "to invest",
    "to sprout",
    "to fight",
    "to edge",
    "to click",
    "to knot",
    "to complicate",
    "to configure",
    "to control",
    "to concentrate",
    "to copy",
    "to correct",
    "to cost",
    "to receive",
    "to crumble",
    "to take care",
    "to load",
    "to dock",
    "to reach",
    "to weigh",
    "to favour",
    "to suffer",
    "to accomplish",
    "to deliver",
    "to link",
    "to list",
    "to blaze",
    "to extinguish",
    "to solve",
    "to mark",
    "to master",
    "to report",
    "to mix",
    "to measure",
    "to share",
    "to complain",
    "to navigate",
    "to standardise",
    "to groove",
    "to utilise",
    "to fit",
    "to happen",
    "to plant",
    "to plan",
    "to polish",
    "to position",
    "to post",
    "to praise",
    "to rehearse",
    "to profit",
    "to check",
    "to score",
    "to qualify",
    "to swell",
    "to frame",
    "to react",
    "to calculate",
    "to count",
    "to assert",
    "to reduce",
    "to regulate",
    "to resolve",
    "to suffice",
    "to ripen",
    "to rescue",
    "to arrange",
    "to trickle",
    "to roll",
    "to move",
    "to call",
    "to collect",
    "to drink",
    "to harm",
    "to switch",
    "to shade",
    "to appreciate",
    "to estimate",
    "to look",
    "to separate",
    "to divorce",
    "to shear",
    "to layer",
    "to send",
    "to strike",
    "to melt",
    "to hurt",
    "to cut",
    "to dart",
    "to embellish",
    "to stride",
    "to owe",
    "to protect",
    "to swell",
    "to sieve",
    "to lower",
    "to store",
    "to ensure",
    "to sift",
    "to act",
    "to care",
    "to split",
    "to save",
    "to save",
    "to store",
    "to track",
    "to originate",
    "to strengthen",
    "to start",
    "to take place",
    "to increase",
    "to die",
    "to control",
    "to vote",
    "to stop",
    "to defer",
    "to fall",
    "to convene",
    "to dance",
    "to participate",
    "to test",
    "to tick",
    "to kill",
    "to drive",
    "to separate",
    "to step",
    "to agree",
    "to overwhelm",
    "to survive",
    "to consider",
    "to overlie",
    "to transmit",
    "to take over",
    "to check",
    "to outshout",
    "to broadcast",
    "to transfer",
    "to monitor",
    "to convince",
    "to kill",
    "to include",
    "to surround",
    "to implement",
    "to succumb",
    "to undertake",
    "to distinguish",
    "to support",
    "to investigate",
    "to change",
    "to improve",
    "to commit",
    "to earn",
    "to deserve",
    "to proceed",
    "to handle",
    "to pursue",
    "to possess",
    "to forget",
    "to compare",
    "to behave",
    "to prevent",
    "to sell",
    "to demand",
    "to award",
    "to avoid",
    "to publish",
    "to reveal",
    "to betray",
    "to decrease",
    "to pass away",
    "to postpone",
    "to cover",
    "to disappear",
    "to equip",
    "to promise",
    "to reinforce",
    "to hide",
    "to defend",
    "to trust",
    "to represent",
    "to manage",
    "to blow away",
    "to waive",
    "to renounce",
    "to prepare",
    "to proceed",
    "to plan",
    "to submit",
    "to be available",
    "to exist",
    "to make",
    "to imagine",
    "to accuse",
    "to dare",
    "to choose",
    "to weave",
    "to change",
    "to point out",
    "to whitewash",
    "to turn",
    "to evaluate",
    "to grasp",
    "to bet",
    "to restore",
    "to repeat",
    "to wave",
    "to prove effective",
    "to amaze",
    "to wish",
    "to pay",
    "to draw",
    "to churn up",
    "to destroy",
    "to aim",
    "to access",
    "to allow",
    "to assign",
    "to match",
    "to collide",
    "to agree",
    "to assign",
];

const myListAdjs = [
    "big",
    "large",
    "small",
    "old",
    "young",
    "new",
    "good",
    "bad",
    "beautiful",
    "ugly",
    "heavy",
    "difficult",
    "light",
    "easy",
    "expensive",
    "cheap",
    "warm",
    "cold",
    "old-fashioned",
    "modern",
    "fast",
    "slow",
    "strong",
    "weak",
    "happy",
    "sad",
    "loud",
    "quiet",
    "clean",
    "dirty",
    "dry",
    "wet",
    "full",
    "empty",
    "friendly",
    "unfriendly",
    "rich",
    "poor",
    "healthy",
    "sick",
    "ill",
    "interesting",
    "boring",
    "simple",
    "easy",
    "complicated",
    "wide",
    "narrow",
    "tight",
    "short",
    "long",
    "tired",
    "awake",
    "pretty",
    "mean",
    "rude",
    "dirty",
    "excited",
    "surprised",
    "beautiful",
    "adventurous",
    "similar",
    "alone",
    "old",
    "poor",
    "annoying",
    "angry",
    "excited",
    "enthusiastic",
    "well known",
    "famous",
    "better",
    "cheap",
    "charming",
    "fat",
    "thick",
    "dark",
    "thin",
    "honest",
    "narrow",
    "serious",
    "fantastic",
    "fascinating",
    "lazy",
    "fine",
    "dilligent",
    "hard working",
    "friendly",
    "happy",
    "pleased",
    "glad",
    "early",
    "patient",
    "brilliant",
    "ingenious",
    "healthy",
    "similar",
    "happy",
    "great",
    "amazing",
    "awesome",
    "big",
    "tall",
    "good",
    "cheap",
    "ugly",
    "gorgeous",
    "superb",
    "hot",
    "bright",
    "helpful",
    "high",
    "polite",
    "interesting",
    "young",
    "cold",
    "small",
    "funny",
    "complicated",
    "long",
    "slow",
    "boring",
    "easy",
    "sweet",
    "sweet",
    "funny",
    "possible",
    "brave",
    "annoying",
    "nervous",
    "nice",
    "new",
    "embarrassing",
    "regular",
    "rich",
    "romantic",
    "calm",
    "quiet",
    "clean",
    "chic",
    "bad",
    "dirty",
    "filthy",
    "fast",
    "lovely",
    "shy",
    "late",
    "spontaneous",
    "strong",
    "proud",
    "likeable",
    "pleasant",
    "expensive",
    "sad",
    "crazy",
    "mad",
    "important",
    "funny",
    "heavy",
    "usual",
    "common",
    "few",
    "little",
    "wonderful",
    "beautiful",
    "whole",
    "all time",
    "first",
    "last",
    "own",
    "additional",
    "exactly",
    "short",
    "correct",
    "different",
    "diverse",
    "special",
    "certain",
    "safe",
    "secure",
    "certain",
    "next",
    "poltical",
    "clear",
    "individual",
    "round",
    "free",
    "variable",
    "clear",
    "general",
    "only",
    "single",
    "mutual",
    "near",
    "close",
    "full",
    "straight",
    "direct",
    "international",
    "social",
    "best",
    "red",
    "open",
    "most",
    "special",
    "certain",
    "public",
    "half",
    "probably",
    "European",
    "Asian",
    "African",
    "essential",
    "fundamental",
    "frequent",
    "black",
    "complete",
    "low",
    "small",
    "practical",
    "personal",
    "modern",
    "deep",
    "real",
    "actual",
    "additional",
    "American",
    "British",
    "German",
    "French",
    "Spanish",
    "Latin",
    "economic",
    "financial",
    "interesting",
    "relative",
    "simultaneous",
    "green",
    "white",
    "whole",
    "entire",
    "special",
    "specific",
    "decisive",
    "technical",
    "constant",
    "necessary",
    "pure",
    "clear",
    "clean",
    "English",
    "scientific",
    "scholarly",
    "wrong",
    "foreign",
    "strange",
    "rare",
    "normal",
    "true",
    "false",
    "private",
    "dead",
    "greedy",
    "slippery",
    "adventurous",
    "dependent",
    "aggressive",
    "clueless",
    "active",
    "adaptable",
    "decent",
    "kind",
    "attractive",
    "enlightened",
    "excited",
    "upset",
    "nervous",
    "open-minded",
    "sincere",
    "genuine",
    "candid",
    "pale",
    "gifted",
    "talented",
    "famous",
    "popular",
    "comfortable",
    "modest",
    "humble",
    "best",
    "enchanting",
    "fascinating",
    "stupid",
    "ignorant",
    "blond",
    "malicious",
    "well-behaved",
    "good",
    "stupid",
    "dumb",
    "ambitious",
    "jealous",
    "conceited",
    "vain",
    "unique",
    "lonely",
    "detestable",
    "nasty",
    "disgusting",
    "gross",
    "dedicated",
    "committed",
    "narrow-minded",
    "laidback",
    "successful",
    "first",
    "first-class",
    "high-quality",
    "topnotch",
    "cowardly",
    "fat",
    "coward",
    "advanced",
    "naughty",
    "cheeky",
    "sassy",
    "cheerful",
    "pious",
    "hospitable",
    "educated",
    "cultured",
    "barbaric",
    "dangerous",
    "sensitive",
    "emotional",
    "witty",
    "brilliant",
    "low",
    "rude",
    "vulgar",
    "just",
    "righteous",
    "dear",
    "valued",
    "clever",
    "bright",
    "talkative",
    "chatty",
    "sociable",
    "friendly",
    "credible",
    "believable",
    "cruel",
    "coarse",
    "uncouth",
    "rude",
    "generous",
    "well-dressed",
    "cheerful",
    "in a good mood",
    "stubborn",
    "hard-headed",
    "stubborn",
    "cheerful",
    "uninhibited",
    "unrestrained",
    "heartless",
    "unfeeling",
    "deceitful",
    "treacherous",
    "haughty",
    "proud",
    "snooty",
    "stuck up",
    "pretty",
    "handsome",
    "dog-tired",
    "idealistic",
    "intelligent",
    "intolerant",
    "childish",
    "childlike",
    "great",
    "super",
    "petty",
    "nit-picky",
    "conservative",
    "sociable",
    "outgoing",
    "strong",
    "creative",
    "critical",
    "crooked",
    "hunched",
    "bent",
    "unstable",
    "frail",
    "moody",
    "temperamental",
    "alive",
    "lively",
    "passionate",
    "quiet",
    "soft",
    "last",
    "lovable",
    "amiable",
    "unusual",
    "strange",
    "distrustful",
    "fashionable",
    "stylish",
    "plump",
    "chubby",
    "moral",
    "ethical",
    "next",
    "careless",
    "negligent",
    "wet",
    "envious",
    "curious",
    "depressed",
    "dejected",
    "cute",
    "low",
    "superficial",
    "shallow",
    "optimistic",
    "passive",
    "partial",
    "biased",
    "one-sided",
    "pessimistic",
    "radical",
    "revolutionary",
    "refined",
    "elegant",
    "rough",
    "rebellious",
    "self-opinionated",
    "honest",
    "mature",
    "religious",
    "huge",
    "ruthless",
    "inconsiderate",
    "considerate",
    "angry",
    "sour",
    "messy",
    "sloppy",
    "clever",
    "cunning",
    "bad",
    "awful",
    "weak",
    "frail",
    "cumbersome",
    "heavy",
    "sluggish",
    "gloomy",
    "melancholic",
    "unselfish",
    "self-confident",
    "selfish",
    "strange",
    "weird",
    "sensational",
    "sensitive",
    "carefree",
    "careful",
    "mocking",
    "scornful",
    "similar",
    "old",
    "enjoyable",
    "present",
    "known",
    "famous",
    "better",
    "specific",
    "definite",
    "certain",
    "colorful",
    "grateful",
    "clear",
    "distinct",
    "obvious",
    "thick",
    "fat",
    "direct",
    "straight",
    "honest",
    "own",
    "proper",
    "single",
    "individual",
    "lone",
    "odd",
    "elegant",
    "sensitive",
    "tight",
    "narrow",
    "close",
    "snug",
    "experienced",
    "firm",
    "flat",
    "shallow",
    "diligent",
    "free",
    "friendly",
    "glad",
    "patient",
    "stingy",
    "together",
    "comfortable",
    "cozy",
    "exact",
    "accurate",
    "precise",
    "straight",
    "right",
    "even",
    "direct",
    "clever",
    "skillful",
    "adept",
    "healthy",
    "certain",
    "sure",
    "smooth",
    "equal",
    "similar",
    "happy",
    "large",
    "big",
    "good",
    "half",
    "hard",
    "frequent",
    "common",
    "hot",
    "bright",
    "high",
    "tall",
    "polite",
    "horizontal",
    "hungry",
    "interesting",
    "broken",
    "clear",
    "smart",
    "intelligent",
    "long",
    "loud",
    "last",
    "funny",
    "amusing",
    "my",
    "possible",
    "tired",
    "close",
    "wet",
    "national",
    "natural",
    "normal",
    "open",
    "open-minded",
    "public",
    "neat",
    "tidy",
    "personal",
    "private",
    "positive",
    "practical",
    "handy",
    "useful",
    "punctual",
    "prompt",
    "on time",
    "right",
    "rich",
    "right",
    "correct",
    "round",
    "gently",
    "clean",
    "fast",
    "beautiful",
    "hard",
    "difficult",
    "safe",
    "certain",
    "sure",
    "social",
    "late",
    "pointed",
    "sharp",
    "spiked",
    "sporty",
    "athletic",
    "fit",
    "strong",
    "sweet",
    "sympathetic",
    "expensive",
    "loyal",
    "true",
    "faithful",
    "different",
    "diverse",
    "varied",
    "many",
    "a lot",
    "full",
    "careful",
    "cautious",
    "probable",
    "plausible",
    "precious",
    "valuable",
    "essential",
    "significant",
    "important",
    "wild",
    "satisfied",
    "content",
    "happy",
];

// ================================================================================================

const someFrequentNouns = [
    "house",
    "school",
    "car",
    "cat",
    "dog",
    "book",
    "friend",
    "work",
    "job",
    "time",
    "child",
    "family",
    "day",
    "night",
    "man",
    "woman",
    "city",
    "country",
    "year",
    "moment",
    "money",
    "home",
    "idea",
    "world",
    "music",
    "life",
    "love",
    "problem",
    "question",
    "answer",
    "story",
    "history",
    "voice",
    "eyes",
    "water",
    "body",
    "heart",
    "table",
    "sun",
    "moon",
    "star",
    "garden",
    "window",
    "door",
    "chair",
    "dream",
    "path",
    "way",
    "friendship",
    "apartment",
];

const topicFamily = [
    "family",
    "mother",
    "father",
    "parents",
    "brother",
    "sister",
    "grandmother",
    "grandfather",
    "grandson",
    "granddaughter",
    "uncle",
    "aunt",
    "cousin (male)",
    "cousin (female)",
    "child",
    "children",
    "husband",
    "wife",
    "siblings",
    "brother-in-law",
    "sister-in-law",
    "nephew",
    "niece",
    "mother-in-law",
    "father-in-law",
    "godfather",
    "godmother",
    "relative",
    "stepmother",
    "stepfather",
    "adopted child",
    "family member",
    "daughter-in-law",
    "son-in-law",
    "stepsister",
    "stepbrother",
    "great-grandchild",
    "great-grandmother",
    "great-grandfather",
    "family celebration",
    "fiancée",
    "fiancé",
    "wedding",
    "marriage",
    "family tree",
    "widow",
    "widower",
    "life partner",
];

const topicBody = [
    "head",
    "face",
    "eye",
    "nose",
    "mouth",
    "ear",
    "neck",
    "throat",
    "shoulder",
    "arm",
    "elbow",
    "hand",
    "finger",
    "thumb",
    "back",
    "chest",
    "stomach",
    "belly",
    "waist",
    "leg",
    "knee",
    "foot",
    "toe",
    "skin",
    "bone",
    "muscle",
    "heart",
    "lung",
    "liver",
    "stomach",
    "kidney",
    "brain",
    "blood",
    "vein",
    "skeleton",
    "tooth",
    "tongue",
    "lip",
    "hip",
    "jaw",
    "joint",
    "tendon",
    "ankle",
    "heel",
    "nail",
    "wrist",
    "diaphragm",
    "spine",
    "hair",
    "eyebrow",
];

const topicGeo = [
    "city",
    "village",
    "country",
    "mountain",
    "lake",
    "river",
    "sea",
    "coast",
    "beach",
    "forest",
    "island",
    "valley",
    "hill",
    "park",
    "garden",
    "square",
    "street",
    "market",
    "train station",
    "airport",
    "bridge",
    "school",
    "university",
    "hospital",
    "church",
    "town hall",
    "castle",
    "museum",
    "theatre",
    "cinema",
    "hotel",
    "restaurant",
    "café",
    "bakery",
    "supermarket",
    "shopping mall",
    "post office",
    "police station",
    "fire station",
    "bank",
    "pharmacy",
    "petrol station",
    "zoo",
    "stadium",
    "swimming pool",
    "library",
    "cemetery",
    "market hall",
    "old town",
    "harbour",
    "port",
    "university town",
    "industrial area",
    "corner",
    "residential area",
    "roundabout",
    "shopping street",
    "motorway",
    "fortress",
    "conservation area",
    "central station",
    "intersection",
    "district",
    "neighbourhood",
    "promenade",
    "town hall square",
    "pedestrian zone",
    "sidewalk",
    "avenue",
    "traffic light",
    "car repair shop",
    "court",
    "kindergarten",
    "roundabout",
    "skyscraper",
    "warehouse",
    "exhibition ground",
    "emergency room",
    "city wall",
    "direction",
    "homeless shelter",
    "parking garage",
    "police station",
    "fire station",
    "skyscraper",
    "ticket counter",
    "tourist information",
    "apartment block",
    "cycle path",
    "fountain",
    "bus stop",
    "bell tower",
    "swamp",
    "desert",
    "highland",
    "glacier",
    "cliff",
    "canyon",
    "oasis",
    "cave",
    "river delta",
    "rock",
    "meadow",
    "starry sky",
    "high mountain range",
    "country road",
    "reed bed",
    "bay",
    "field",
    "plain",
    "mountain range",
    "lagoon",
    "fjord",
    "ridge",
];

const someExpressions = [
    "Good morning",
    "Good day",
    "Good evening",
    "Good night",
    "Hello",
    "Bye",
    "Goodbye",
    "How are you?",
    "I am fine",
    "Thank you",
    "Please",
    "Excuse me",
    "No problem",
    "I am sorry",
];

const topicAnimals = [
    "Dog",
    "Cat",
    "Horse",
    "Bird",
    "Fish",
    "Rabbit",
    "Hamster",
    "Pig",
    "Cow",
    "Sheep",
    "Goat",
    "Mouse",
    "Rat",
    "Donkey",
    "Hare",
    "Bear",
    "Lion",
    "Tiger",
    "Eagle",
    "Dolphin",
    "Snake",
    "Crocodile",
    "Wolf",
    "Bat",
    "Penguin",
    "Sea lion",
    "Whale",
    "Owl",
    "Cattle",
    "Chicken",
    "Duck",
    "Goose",
    "Dove",
    "Ant",
    "Butterfly",
    "Wasp",
    "Mosquito",
    "Spider",
    "Worm",
    "Fly",
    "Beetle",
    "Dragonfly",
    "Snail",
    "Shell",
    "Squid",
    "Starfish",
    "Jellyfish",
    "Rhinoceros",
    "Cheetah",
    "Monkey",
    "Kangaroo",
    "Koala",
    "Panda",
];

const topicFoodDrinks = [
    "Apple",
    "Banana",
    "Orange",
    "Grape",
    "Strawberry",
    "Cherry",
    "Melon",
    "Peach",
    "Pineapple",
    "Kiwi",
    "Carrot",
    "Tomato",
    "Onion",
    "Garlic",
    "Potato",
    "Rice",
    "Pasta",
    "Bread",
    "Butter",
    "Cheese",
    "Yoghurt",
    "Milk",
    "Juice",
    "Water",
    "Tea",
    "Coffee",
    "Beer",
    "Wine",
    "Champagne",
    "Soup",
    "Salad",
    "Sandwich",
    "Burger",
    "Pizza",
    "Cookie",
    "Cake",
    "Ice cream",
    "Chocolate",
    "Honey",
    "Jam",
    "Nuts",
    "Chips",
    "Popcorn",
    "Cinnamon",
    "Vanilla",
    "Pumpkin",
    "Zucchini",
    "Eggplant",
    "Bell pepper",
    "Cucumber",
    "Radish",
    "Asparagus",
    "Cauliflower",
    "Broccoli",
    "Mushroom",
    "Lamb",
    "Beef",
    "Pork",
    "Chicken",
    "Salmon",
    "Tuna",
    "Mussels",
    "Shrimp",
    "Tofu",
    "Cream",
    "Quark",
    "Feta cheese",
    "Parmesan cheese",
    "Mozzarella cheese",
    "Olive oil",
    "Vinegar",
    "Salt",
    "Pepper",
    "Sugar",
    "Syrup",
    "Mustard",
    "Ketchup",
    "Mayonnaise",
    "Broth",
    "Cookies",
    "Pudding",
    "Tart",
    "Croissant",
    "Bagel",
];

const topicHome = [
    "House",
    "Apartment",
    "Room",
    "Kitchen",
    "Bathroom",
    "Bedroom",
    "Living room",
    "Dining room",
    "Hallway",
    "Balcony",
    "Garage",
    "Basement",
    "Roof",
    "Window",
    "Door",
    "Wall",
    "Floor",
    "Carpet",
    "Furniture",
    "Sofa",
    "Chair",
    "Table",
    "Cabinet",
    "Closet",
    "Shelf",
    "Lamp",
    "Television",
    "Stove",
    "Refrigerator",
    "Washing machine",
    "Dishwasher",
    "Microwave",
    "Burner",
    "Sink",
    "Kettle",
    "Toaster",
    "Coffee machine",
    "Bed",
    "Pillow",
    "Blanket",
    "Nightstand",
    "Curtain",
    "Drapes",
    "Heating",
    "Air conditioning",
    "Telephone",
    "Router",
    "Mailbox",
    "Key",
    "Carpet flooring",
    "Entrance hall",
    "Storage room",
    "Guest room",
    "Tiles",
    "Attic",
    "Fireplace",
    "Roller shutter",
    "Awning",
    "Stairs",
    "Towel",
    "Bed linen",
    "Bathtub",
    "Shower",
    "Washbasin",
    "Toilet",
    "Bin",
    "Vacuum cleaner",
    "Cleaning agent",
    "Cloth",
    "Smoke detector",
    "Alarm system",
    "Wardrobe",
    "Iron",
    "Hairdryer",
    "Toothbrush",
    "Toothpaste",
    "Soap",
    "Dish soap",
    "Cleaner",
    "Laundry basket",
    "Bookshelf",
    "Desk",
    "Dresser",
    "Mirror",
    "Armchair",
    "TV stand",
    "Artwork",
    "Display cabinet",
    "Flower pot",
    "Clothesline",
    "Bed frame",
    "Pillow",
    "Ceiling light",
    "Table lamp",
    "Candle holder",
    "Photo frame",
    "Door knocker",
    "Key holder",
    "Clothes hanger",
    "Mattress",
    "Nightstand lamp",
    "Bookshelf",
];

const topicClothes = [
    "Shirt",
    "Blouse",
    "T-shirt",
    "Sweater",
    "Jacket",
    "Coat",
    "Trousers",
    "Pants",
    "Jeans",
    "Shorts",
    "Skirt",
    "Dress",
    "Suit",
    "Tie",
    "Scarf",
    "Gloves",
    "Hat",
    "Cap",
    "Socks",
    "Underwear",
    "Bra",
    "Boxer shorts",
    "Pyjamas",
    "Swimsuit",
    "Bathrobe",
    "Shoes",
    "Boots",
    "Sandals",
    "Slippers",
    "Belt",
    "Bag",
    "Backpack",
    "Suitcase",
    "Cloak",
    "Tights",
    "Sock",
    "Shirt collar",
    "Waistcoat",
    "Hoodie",
    "Cardigan",
    "Leggings",
    "Overalls",
    "Pajamas",
    "Anorak",
    "Headband",
    "Dungarees",
    "Tie pin",
    "Hair tie",
    "Sunglasses",
    "Earrings",
    "Wristwatch",
    "Apron",
    "Swimming trunks",
    "Arm warmers",
    "Bonnet",
    "Pinafore dress",
    "Fleece jacket",
    "Turtleneck sweater",
    "Down jacket",
    "Blazer",
    "Swim cap",
    "Garters",
    "Fedora",
    "Vest",
    "Sock garter",
    "Wrap skirt",
];

const topicDirections = [
    "Straight ahead",
    "Right",
    "Left",
    "To turn",
    "Straight",
    "Up to",
    "Opposite",
    "Between",
    "Near",
    "Far",
    "Turn right",
    "Turn left",
    "Way",
    "Directions",
    "Roundabout",
    "One-way street",
    "Dead end",
    "Access",
    "Parking lot",
    "To cross",
    "On the right side",
    "On the left side",
    "On the opposite side",
    "Under",
    "Up",
    "above",
    "Down",
    "below",
    "Along",
    "Opposite to",
    "Turn into",
    "Continue driving",
    "At the corner",
    "Along the street",
    "Opposite the church",
    "Upwards",
    "Downwards",
    "At the right corner",
    "Near",
    "On the opposite side of the street",
];

const topicTime = [
    "Clock",
    "Watch",
    "Time",
    "Hour",
    "Minute",
    "Second",
    "Morning",
    "Afternoon",
    "Evening",
    "Night",
    "Time",
    "Quarter",
    "Half",
    "O’clock",
    "Appointment",
    "Schedule",
    "Deadline",
    "Year",
    "Month",
    "Week",
    "Day",
    "Today",
    "Yesterday",
    "Tomorrow",
    "Weekend",
    "Duration",
    "Duration",
    "Alarm clock",
    "Time indication",
    "Moment",
    "Time zone",
    "Time difference",
    "On time",
    "Delay",
    "Clock hands",
    "Planner",
    "Noon",
    "Time management",
    "Period",
    "Hour",
    "Time frame",
    "Timer",
    "Last week",
    "Next week",
    "Timetable",
    "Calendar",
    "Appointment",
    "Time frame",
    "Duration",
];

const topicMaterials = [
    "Wood",
    "Metal",
    "Glass",
    "Plastic",
    "Paper",
    "Fabric",
    "Leather",
    "Stone",
    "Concrete",
    "Ceramic",
    "Textile",
    "Wool",
    "Cotton",
    "Silk",
    "Rubber",
    "Aluminium",
    "Zinc",
    "Copper",
    "Bronze",
    "Marble",
    "Foam",
    "Linen",
    "Foil",
    "Wire",
    "Rope",
    "Slate",
    "Asbestos",
    "Cardboard",
    "Felt",
    "Brick",
    "Cloth",
    "Plexiglass",
    "Rattan",
    "Sisal",
    "Jute",
    "Filament",
    "Silver",
    "Titanium",
    "Carbon",
    "Mica",
    "Cowhide leather",
];

const topicNumbers = [
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Twenty",
    "Thirty",
    "Forty",
    "Fifty",
    "Sixty",
    "Seventy",
    "Eighty",
    "Ninety",
    "Hundred",
    "Thousand",
    "Ten thousand",
    "Hundred thousand",
    "One million",
    "Two million",
    "Third",
    "Quarter",
    "Half",
    "Whole",
    "Several",
    "A few",
    "All",
    "Nothing",
    "Many",
    "Some",
    "Few",
    "More",
    "Less",
    "First",
    "Last",
    "Before",
    "After",
    "Now",
    "Later",
    "Today",
    "Yesterday",
    "Tomorrow",
    "Sixty-two",
    "Seventy-eight",
    "Thirty-two",
    "One hundred sixty-eight",
    "Two hundred forty-five",
];

const topicReligion = [
    "God",
    "Church",
    "Prayer",
    "Bible",
    "Quran",
    "Cross",
    "Holy Spirit",
    "Gospel",
    "Sin",
    "Baptism",
    "Pastor",
    "Minister",
    "Congregation",
    "Worship Service",
    "Altar",
    "Sacrament",
    "Sermon",
    "Messiah",
    "Heaven",
    "Hell",
    "Prayer Book",
    "Holy Scripture",
    "Fasting",
    "Pilgrimage",
    "Blessing",
    "Confirmation",
];

const topicFrequency = [
    "Always",
    "Never",
    "Often",
    "Sometimes",
    "Rarely",
    "Now",
    "Soon",
    "Earlier",
    "Later",
    "Every time",
    "Occasionally",
    "Today",
    "Tomorrow",
    "Yesterday",
    "The day after tomorrow",
    "Again and again",
    "As soon as",
    "Just",
    "Right now",
    "Forever",
    "Often",
    "As usual",
    "Rarely",
    "In the long run",
    "Usually",
    "Occasionally",
    "Finally",
    "At the moment",
    "Regularly",
    "Still",
    "Constantly",
    "Frequently",
    "As a rule",
    "Once",
    "Regularly",
    "If possible",
];

const topicUrgency = [
    "Immediately",
    "Directly",
    "Immediately",
    "Quickly",
    "Now",
    "Urgent",
    "Immediate",
    "Without delay",
    "Promptly",
    "Urgently",
    "On the spot",
    "Right now",
];

const topicInformal = [
    "Piss off!",
    "Really?",
    "What the hell?",
    "Shit!",
    "Damn!",
    "Damn!",
    "What a mess!",
    "Damn it!",
    "Great!",
    "You're crazy!",
    "What’s the bullshit?",
    "Come on!",
    "Shut up!",
    "Forget it!",
    "Are you crazy?",
    "That’s amazing!",
    "You can't be serious!",
    "What do you want?",
    "Come on, hurry up!",
    "Pardon?",
    "Go away!",
    "Crazy!",
    "Intense!",
    "No idea!",
    "What’s up?",
    "I think I’m going crazy.",
];

const topicSwearWords = [
    "Shit",
    "Damn",
    "Shit",
    "Damn",
    "Asshole",
    "Stupid",
    "Forget it!",
    "Damn it!",
    "Complete idiot",
    "Crap",
    "Pig!",
    "Son of a bitch",
    "Piece of shit",
    "To mess up",
    "To screw up",
    "Damn asshole",
    "Doesn't matter",
    "Who cares",
    "Fuck you!",
    "Whore",
    "To vomit",
    "Slut",
];

const topicUnsorted = ["You too", "Have a good day", "Take care", "until then", "depends on", "you're welcome"];

// ================================================================================================

const topicPrepositions = [
    "in",
    "into",
    "on",
    "at",
    "with",
    "after",
    "to",
    "from",
    "of",
    "over",
    "about",
    "under",
    "beneath",
    "through",
    "by",
    "before",
    "in front of",
    "from",
    "out of",
    "around",
    "about",
    "past",
    "until",
    "by",

    "with",
    "for",
    "against",
    "without",
    "from",
    "to",
    "between",
    "along",
    "despite",
    "during",
    "because of",
    "since",
    "except",
    "behind",
    "next to",
    "opposite",
    "across from",
    "due to",
    "below",
    "above",
    "within",
    "outside of",
    "after",
    "since",
    "on the occasion of",
    "based on",
    "instead of",
    "with the help of",
    "contrary to",
    "per",
    "according to",
    "in favour of",
];

const topicConjunctions = [
    "and",
    "or",
    "but",
    "because",
    "that",
    "when",
    "whether",
    "as well as",
    "therefore",
    "so that",
    "in case",
    "if",
    "although",
    "as soon as",
    "before",
    "either...or",
    "both...and",
    "neither...nor",
    "as long as",
    "by",
    "so that",
    "nevertheless",
    "the...the",
    "therefore",
    "however",
    "especially as",
    "how",
    "as",
    "for example",
    "provided that",
    "yet",
    "but",
    "even though",
    "nevertheless",
    "meanwhile",
    "although",
    "although",
    "since",
    "also",
    "meanwhile",
];

const topicGlueWords = [
    "however",
    "besides",
    "only",
    "also",
    "too",
    "so",
    "that",
    "not only ... but also",
    "but also",
    "first",
    "afterwards",
    "finally",
    "ultimately",
    "unless",
    "either ... or",
    "lastly",
];

const topicBasicPhrases = [
    "Hello",
    "Good morning",
    "Good day",
    "Good evening",
    "Good night",
    "Bye (informal)",
    "Goodbye",
    "Please",
    "Thank you",
    "Excuse me",
    "Sorry",
    "I don't understand",
    "Do you speak English?",
    "How much does it cost?",
    "Where is...?",
    "I would like...",
    "I am lost",
    "What time is it?",
    "I have a reservation",
    "I need help",
    "Can you please repeat that?",
    "What do you recommend?",
    "I am allergic to...",
    "What does that mean?",
    "What is your phone number?",
    "I would like to pay",
    "Where can I find a taxi?",
    "I am hungry",
    "I am tired",
    "I'm sorry",
    "Congratulations!",
    "Good luck!",
    "I am looking forward to",
    "Can you please show me the way?",
    "It is very nice here.",
    "How long does it take?",
    "I am from...",
    "I speak only a little German.",
    "Can you please give me a receipt?",
    "I would like to book a room.",
    "I have a question.",
    "What is the admission fee?",
];

const mixed = [
    "love",
    "happiness",
    "joy",
    "fun",
    "city",
    "street",
    "work",
    "language",
    "question",
    "answer",
    "time",
    "date",
    "day",
    "week",
    "month",
    "year",
    "book",
    "water",
    "art",
    "room",
    "light",
    "opinion",
    "mistake",
    "color",
    "word",
    "on",
    "it",
    "and",
    "to",
    "on",
    "with",
    "for",
    "from",
    "itself",
    "this",
    "also",
    "he",
    "not",
    "at",
    "to be able",
    "we",
    "out",
    "to give",
    "I",
    "her",
    "should, to have to",
    "after",
    "around",
    "still",
    "but",
    "no",
    "above",
    "new",
    "to come",
    "here",
    "only",
    "before",
    "to go, to walk",
    "through",
    "percent",
    "then",
    "so",
    "to stand",
    "year",
    "to lie, to be located",
    "to have to",
    "now",
    "to find",
    "wide, large, far",
    "to want",
    "now",
    "what",
    "our",
    "to make",
    "how",
    "as",
    "very",
    "again",
    "already",
    "to remain",
    "first",
    "under",
    "from",
    "to see",
    "always",
    "nearby, besides",
    "there",
    "more",
    "against",
    "there",
    "German",
    "everyone",
    "however, certainly",
    "or",
    "until",
    "man",
    "to begin",
    "two",
    "entire",
    "today",
    "already",
    "in order to",
    "my",
    "so",
    "high",
    "however",
    "time",
    "o'clock",
    "in addition",
    "further",
    "in addition to",
    "to be valid",
    "both",
    "day",
    "to happen",
    "since",
    "natural",
    "everyone",
    "to receive",
    "to point at",
    "to climb, to rise",
    "to place",
    "to lead",
    "to fall",
    "to be",
    "to belong",
    "round",
    "important",
    "child",
    "moreover",
    "page",
    "man",
    "a lot of",
    "you",
    "old",
    "us",
    "to speak",
    "woman",
    "other",
    "company",
    "for that",
    "without",
    "three",
    "to hold",
    "yes",
    "possible",
    "a million",
    "easy",
    "point",
    "to offer",
    "to bring",
    "police",
    "to succeed",
    "in between",
    "to be allowed to",
    "back",
    "next",
    "problem",
    "second",
    "to play",
    "something",
    "picture",
    "instead of",
    "result",
    "own",
    "case",
    "which one",
    "to run",
    "some",
    "first",
    "price",
    "city",
    "currently",
    "them",
    "to put",
    "to expect",
    "to lay",
    "also",
    "to say",
    "to reach",
    "strong",
    "end",
    "develop",
    "country",
    "question",
    "house",
    "him",
    "game",
    "to need",
    "overall",
    "please",
    "him",
    "because of",
    "first",
    "week",
    "to demand",
    "to follow",
    "life",
    "approximately",
    "me",
    "last",
    "not heavy, easy",
    "corresponding",
    "work",
    "to occupy a place",
    "long",
    "part",
    "reason",
    "to plan",
    "information",
    "personally",
    "to lack",
    "money",
    "to search",
    "beautiful",
    "correct",
    "Germany",
    "even",
    "to win",
    "quick",
    "to lose",
    "times",
    "difficult, heavy",
    "to work",
    "in the end",
    "to pull",
    "different",
    "actually",
    "so far",
    "number",
    "then",
    "offer",
    "program",
    "to meet",
    "known",
    "who",
    "hour",
    "to let",
    "to do",
    "path",
    "to die",
    "especially",
    "therefore",
    "nearly",
    "world",
    "name",
    "through it",
    "to get",
    "in the meantime",
    "story",
    "to take over",
    "to carry",
    "share",
    "decision",
    "goal",
    "thereafter",
    "nothing",
    "month",
    "to drive",
    "firm",
    "anyhow",
    "late",
    "success",
    "clear",
    "to confirm",
    "to name",
    "current",
    "place",
    "to cost",
    "perhaps",
    "less",
    "topic",
    "me",
    "several",
    "to worry",
    "to live",
    "minute",
    "once",
    "example",
    "short",
    "location",
    "young",
    "to help",
    "equal, same",
    "four",
    "cost",
    "to create",
    "exact",
    "family",
    "project",
    "to last",
    "to choose",
    "to count",
    "to act",
    "to form",
    "employee",
    "to decide",
    "never",
    "school",
    "so far",
    "consequence, sequence",
    "member",
    "usage",
    "to shut down",
    "market",
    "at that time, in those days",
    "worth",
    "differing",
    "to start",
    "to write",
    "Berlin",
    "total",
    "five",
    "to count",
    "to grow",
    "unfortunately",
    "future",
    "from it",
    "additional",
    "to share",
    "together",
    "to support",
    "often",
    "full",
    "free",
    "development",
    "still",
    "internet",
    "to be named, to mean",
    "early",
    "to step",
    "association",
    "special",
    "to hurt",
    "to relate",
    "single",
    "to use",
    "different",
    "hardly",
    "group",
    "probably",
    "book",
    "role",
    "hand",
    "bad",
    "conversation",
    "immediately",
    "customer",
    "to sink",
    "to know",
    "even",
    "where",
    "turnover",
    "person",
    "May - the month",
    "billion",
    "behind",
    "to change",
    "open",
    "to know",
    "real",
    "against it",
    "afterwards",
    "third",
    "next to, alongside",
    "a right",
    "September",
    "to threaten",
    "government",
    "place",
    "gladly, with pleasure",
    "to point",
    "to wait",
    "one",
    "to correspond",
    "indication",
    "numerous",
    "such",
    "to use",
    "while",
    "area",
    "possibility",
    "bank",
    "answer",
    "team",
    "positive",
    "word",
    "past",
    "to gladden",
    "to contain",
    "street",
    "to appear",
    "to reach, to suffice",
    "Friday",
    "therefore",
    "Thursday",
    "date",
    "from there",
    "disposal",
    "to end",
    "international",
    "secure, certain",
    "rather",
    "team",
    "to develop",
    "loyal",
    "doer",
    "direct",
    "to heighten",
    "yesterday",
    "evening",
    "common",
    "chance",
    "help",
    "criticism",
    "company",
    "to offer",
    "damage",
    "political",
    "renewed",
    "clear",
    "solution",
    "European",
    "April",
    "event",
    "situation",
    "to celebrate",
    "film",
    "thing, affair",
    "to build",
    "anyhow, nevertheless",
    "to want",
    "to sit",
    "October",
    "complete",
    "glance",
    "water",
    "to think",
    "to concern",
    "why",
    "soon",
    "January",
    "business",
    "church",
    "task",
    "opposite to",
    "following",
    "Monday",
    "to function",
    "to require",
    "idea",
    "to plan, to provide",
    "to open",
    "title",
    "to mean",
    "June",
    "Sunday",
    "car",
    "vehicle",
    "to react",
    "building",
    "to end",
    "to hit",
    "to determine",
    "March",
    "procedure",
    "noisy",
    "successful",
    "room",
    "step",
    "choice, election",
    "municipality",
    "complete",
    "six",
    "little",
    "finite",
    "beginning",
    "to put in",
    "inside",
    "guest",
    "ten",
    "merely",
    "wish",
    "course",
    "per",
    "date",
    "little",
    "flat",
    "similar",
    "system",
    "student",
    "experience",
    "difficult",
    "victim",
    "upon that, after that",
    "participant",
    "to inform",
    "meter",
    "politics",
    "otherwise",
    "to ask",
    "animal",
    "to descend",
    "report",
    "to ascertain",
    "plan",
    "to finish",
    "meanwhile",
    "rule",
    "to succeed",
    "alone",
    "parent",
    "to give birth",
    "eye",
    "judgment",
    "to occupy, to employ",
    "November",
    "in each case",
    "music",
    "to serve",
    "public",
    "Berliner",
    "hard",
    "height",
    "to perform",
    "to rule",
    "to open",
    "to be right",
    "at all, even",
    "most of",
    "visitor",
    "to prevent",
    "state",
    "Wednesday",
    "to join",
    "to happen",
    "authentic",
    "February",
    "to pick up",
    "you",
    "head",
    "to decay, to rot",
    "to decree",
    "court",
    "without cost",
    "to report",
    "Tuesday",
    "border",
    "only",
    "in addition",
    "interesting",
    "August",
    "interest",
    "July",
    "type, kind",
    "namely",
    "to pay",
    "contract",
    "necessary",
    "performance",
    "pressure",
    "to break",
    "text",
    "before",
    "people",
    "December",
    "fun",
    "photo",
    "to supply",
    "party",
    "mark",
    "fire brigade",
    "to put",
    "false",
    "fear",
    "content",
    "to own",
    "to change",
    "region",
    "to work",
    "to publish",
    "society",
    "player",
    "available",
    "website",
    "to look",
    "counter",
    "voice, vote",
    "sometimes",
    "detail",
    "to lean",
    "to set up",
    "to estimate",
    "eight",
    "request",
    "long",
    "facility",
    "to shine",
    "in any case",
    "at all",
    "to hope",
    "respective",
    "personal",
    "accusation",
    "scarce",
    "to solve, to loosen",
    "safety",
    "study",
    "product",
    "simultaneous",
    "to understand",
    "investigation",
    "to make possible",
    "card",
    "century",
    "youthful",
    "great",
    "contribution",
    "to hang",
    "operation",
    "to direct",
    "this time",
    "door",
    "to encompass",
    "over",
    "necessary",
    "seven",
    "to hear",
    "nobody",
    "proposal",
    "your",
    "to recognize",
    "considerable",
    "to enhance",
    "measure, tactic",
    "slow",
    "board of directors",
    "officer",
    "paper",
    "absolute",
    "gate",
    "law",
    "doctor",
    "face",
    "night",
    "business group",
    "quality",
    "ever",
    "otherwise",
    "special",
    "to visit",
    "above it, about it",
    "device",
    "partially",
    "Saturday",
    "official",
    "negotiation",
    "rest",
    "rare",
    "to sell",
    "support",
    "pure",
    "to present",
    "to call",
    "residence, apartment",
    "union",
    "selection",
    "certain",
    "victory",
    "to give notice, to cancel a contract",
    "concept",
    "stock exchange",
    "driver",
    "girl",
    "investigation",
    "by",
    "background",
    "power",
    "form",
    "namely",
    "federal government",
    "war",
    "to secure",
    "worldwide",
    "mother",
    "to represent, to introduce",
    "deed",
    "to happen",
    "to get lost",
    "profit",
    "to learn",
    "to close off, to bar",
    "to ask for",
    "individual",
    "cause",
    "thereupon",
    "to read",
    "previous",
    "German",
    "technical",
    "economy",
    "to achieve",
    "decisive",
    "to warn",
    "language",
    "focus",
    "dear",
    "private",
    "to shape",
    "public prosecutor's office",
    "to suffer",
    "God",
    "expert",
    "situation",
    "risk",
    "mood",
    "accident",
    "complete",
    "to use",
    "just the same, equally",
    "action",
    "many",
    "summer",
    "advantage",
    "finally",
    "to found, to establish",
    "discussion",
    "weak",
    "to love",
    "to create",
    "color",
    "danger",
    "constant",
    "band",
    "to fail",
    "man",
    "at least",
    "to examine",
    "exhibition",
    "direction",
    "red",
    "assumption, requirement",
    "green",
    "there",
    "list",
    "daily",
    "necessary",
    "to conclude",
    "frequent",
    "basis",
    "fight",
    "tangible",
    "sense",
    "afternoon",
    "coach",
    "death",
    "mistake",
    "search",
    "construction",
    "wide",
    "model",
    "to further",
    "window",
    "class",
    "friend",
    "visit",
    "ordinary",
    "authority",
    "to exclude",
    "analyst",
    "quiet",
    "news",
    "to allow, to let",
    "season",
    "to turn out",
    "competition",
    "at least",
    "experienced",
    "contact",
    "father",
    "crisis",
    "expectation",
    "to benefit",
    "train",
    "to continue",
    "to suffer",
    "to establish",
    "weekend",
    "to criticize",
    "work",
    "to change",
    "loss",
    "modification",
    "medium",
    "piece",
    "today's",
    "satisfied",
    "love",
    "route, railway",
    "black",
    "long ago",
    "Hamburg",
    "to wish",
    "meaning",
    "deep",
    "damage",
    "to explain",
    "on the other hand",
    "gladly",
    "opinion",
    "at the same time",
    "warm",
    "cooperation",
    "actual",
    "newspaper",
    "quite",
    "in it",
    "to defend",
    "off",
    "journey",
    "fundamental, on principle",
    "trend",
    "to perform a task",
    "to disappear",
    "to think",
    "to represent",
    "to move",
    "technology",
    "in spite of",
    "time",
    "body",
    "difference",
    "majority",
    "to treat",
    "material",
    "round",
    "air",
    "to welcome",
    "fan",
    "degree",
    "trace",
    "to turn",
    "to believe",
    "to extend",
    "alternative",
    "agent",
    "workplace",
    "to express",
    "Europe",
    "to fill",
    "weather",
    "ground",
    "to experience",
    "hint",
    "first",
    "so-called",
    "apparent",
    "when",
    "Munich",
    "dispute",
    "to throw",
    "to discover",
    "start",
    "beginning",
    "to leave",
    "morning",
    "ready",
    "competent",
    "to lead",
    "quantity",
    "light",
    "financial",
    "American",
    "to save up",
    "for the first time",
    "final",
    "in particular",
    "credit",
    "frame",
    "favourable",
    "planned",
    "production",
    "significant",
    "to organize",
    "fire",
    "injury",
    "soldier",
    "restrained",
    "to arrest",
    "exclusive",
    "function",
    "viewer",
    "dangerous",
    "to operate",
    "Michael",
    "tree",
    "to pay",
    "to participate",
    "constantly",
    "control",
    "close",
    "feeling",
    "economical",
    "registration",
    "to display",
    "previous year",
    "to accompany",
    "dream",
    "social",
    "assignment",
    "car",
    "to check",
    "hereto",
    "regular",
    "citizen",
    "change",
    "edition",
    "village",
    "to describe",
    "historical",
    "you",
    "comparison",
    "process",
    "away",
    "row",
    "manufacturer",
    "to document",
    "happiness",
    "facility",
    "to fight",
    "middle",
    "president",
    "boy",
    "active",
    "to avoid",
    "effect",
    "absolutely",
    "regulation",
    "education",
    "to forbid",
    "trade",
    "narrow",
    "to grab",
    "to climb",
    "treatment",
    "demand",
    "to destroy",
    "protection",
    "article",
    "automatic",
    "service",
    "audience",
    "population",
    "to discuss",
    "parliament",
    "always",
    "route",
    "protest",
    "rather",
    "meanwhile",
    "a demand",
    "extensive",
    "leadership",
    "central",
    "yearly",
    "computer",
    "solid",
    "to talk",
    "motion",
    "to buy",
    "to rescue",
    "preparation",
    "opponent",
    "nine",
    "to allow",
    "lawful",
    "dog",
    "to earn",
    "to determine",
    "share",
    "art",
    "hotel",
    "had to",
    "to fit",
    "idea",
    "ride",
    "such as",
    "to feel",
    "to sound",
    "to the right",
    "extensive",
    "half",
    "to ring",
    "examination",
    "industry",
    "Peter",
    "to recommend",
    "to investigate",
    "time",
    "growth",
    "position",
    "Russian",
    "possibly",
    "responsibility",
    "request",
    "to decline",
    "by the way, apart from that",
    "exception",
    "to request",
    "hereby",
    "reaction",
    "to remind",
    "to push",
    "to reside",
    "room",
    "to agree",
    "anyhow, after all",
    "many, some",
    "match",
    "former",
    "discussion",
    "to raise",
    "suspected",
    "sale",
    "practical",
    "unclear",
    "unambiguous",
    "coalition",
    "line",
    "however",
    "museum",
    "to pursue",
    "to endanger",
    "to order",
    "sudden",
    "partner",
    "to require",
    "claim, demand",
    "Thomas",
    "to facilitate",
    "to load",
    "way",
    "police",
    "joy",
    "sign",
    "rise",
    "planning",
    "ship",
    "suitable",
    "because of",
    "nature",
    "to clear up",
    "instead",
    "sharp",
    "remaining, residual",
    "construction",
    "low",
    "to give up",
    "nearness",
    "to run",
    "a Swiss person",
    "to tell",
    "to extend",
    "to reduce",
    "empty",
    "true",
    "autumn",
    "anytime, always",
    "to fly",
    "gigantic",
    "the",
    "to be",
    "and",
    "to",
    "of",
    "a",
    "I",
    "in",
    "to have",
    "that",
    "he",
    "not",
    "his",
    "her",
    "it",
    "you",
    "with",
    "for",
    "to do",
    "she",
    "as",
    "on",
    "to say",
    "at",
    "him",
    "from",
    "but",
    "me",
    "my",
    "to go",
    "they",
    "all",
    "by",
    "this",
    "one",
    "out",
    "up",
    "to know",
    "an",
    "to see",
    "could",
    "or",
    "them",
    "to get",
    "we",
    "like",
    "to come",
    "man",
    "what",
    "to make",
    "there",
    "about",
    "which",
    "their",
    "into",
    "to think",
    "to look",
    "if",
    "who",
    "when",
    "to take",
    "time",
    "no",
    "back",
    "to can",
    "to will",
    "your",
    "more",
    "then",
    "down",
    "good",
    "over",
    "to tell",
    "now",
    "hand",
    "some",
    "to want",
    "just",
    "only",
    "than",
    "way",
    "to give",
    "other",
    "day",
    "eye",
    "before",
    "to ask",
    "to find",
    "two",
    "little",
    "long",
    "very",
    "to feel",
    "any",
    "thing",
    "too",
    "here",
    "never",
    "to leave",
    "person",
    "old",
    "head",
    "to turn",
    "again",
    "through",
    "even",
    "face",
    "much",
    "off",
    "us",
    "first",
    "right",
    "our",
    "how",
    "where",
    "after",
    "its",
    "woman",
    "away",
    "life",
    "to seem",
    "to call",
    "still",
    "to hear",
    "year",
    "own",
    "to work",
    "should",
    "place",
    "room",
    "well",
    "to stand",
    "to must",
    "himself",
    "around",
    "door",
    "to might",
    "something",
    "to try",
    "to love",
    "house",
    "night",
    "to put",
    "great",
    "such",
    "to keep",
    "to sit",
    "last",
    "to begin",
    "because",
    "those",
    "these",
    "word",
    "to use",
    "to need",
    "to open",
    "to hold",
    "another",
    "while",
    "most",
    "to talk",
    "to let",
    "upon",
    "far",
    "without",
    "home",
    "to smile",
    "always",
    "voice",
    "child",
    "father",
    "to walk",
    "young",
    "to mean",
    "nothing",
    "to run",
    "though",
    "moment",
    "against",
    "mother",
    "same",
    "name",
    "to speak",
    "many",
    "mind",
    "few",
    "to bring",
    "light",
    "to close",
    "side",
    "ever",
    "to move",
    "to may",
    "friend",
    "every",
    "arm",
    "three",
    "once",
    "enough",
    "to become",
    "girl",
    "under",
    "new",
    "end",
    "to live",
    "also",
    "to help",
    "between",
    "world",
    "to fall",
    "to start",
    "each",
    "to wait",
    "to watch",
    "to stop",
    "anything",
    "both",
    "foot",
    "part",
    "small",
    "until",
    "really",
    "to answer",
    "to show",
    "boy",
    "herself",
    "to lie",
    "sure",
    "course",
    "to happen",
    "to believe",
    "to return",
    "behind",
    "point",
    "next",
    "yet",
    "heart",
    "water",
    "almost",
    "to set",
    "body",
    "why",
    "to pass",
    "morning",
    "hour",
    "sound",
    "to meet",
    "God",
    "white",
    "to remember",
    "kind",
    "to hope",
    "to reach",
    "to die",
    "hard",
    "bad",
    "half",
    "to laugh",
    "family",
    "since",
    "high",
    "book",
    "matter",
    "step",
    "to change",
    "question",
    "across",
    "to understand",
    "to follow",
    "together",
    "wife",
    "to pull",
    "along",
    "table",
    "to play",
    "to lose",
    "big",
    "to cry",
    "black",
    "hair",
    "to read",
    "front",
    "to send",
    "quite",
    "to break",
    "myself",
    "to shall",
    "already",
    "minute",
    "dark",
    "soon",
    "bed",
    "toward",
    "whole",
    "car",
    "window",
    "to shake",
    "else",
    "rest",
    "money",
    "fact",
    "son",
    "to write",
    "fire",
    "second",
    "to stay",
    "to wonder",
    "case",
    "story",
    "line",
    "to grow",
    "air",
    "to wish",
    "thought",
    "to rise",
    "least",
    "full",
    "to catch",
    "to lead",
    "large",
    "to appear",
    "everything",
    "to care",
    "to carry",
    "death",
    "to sleep",
    "to kill",
    "idea",
    "to reply",
    "to wear",
    "wall",
    "to drive",
    "near",
    "to draw",
    "shoulder",
    "week",
    "past",
    "dead",
    "early",
    "to stare",
    "alone",
    "sense",
    "mouth",
    "rather",
    "to bear",
    "four",
    "to continue",
    "tree",
    "brother",
    "reason",
    "horse",
    "others",
    "order",
    "lot",
    "five",
    "to touch",
    "round",
    "deep",
    "letter",
    "Miss",
    "to suppose",
    "force",
    "town",
    "to eat",
    "clear",
    "to marry",
    "to throw",
    "country",
    "present",
    "inside",
    "floor",
    "to pay",
    "to nod",
    "finger",
    "to remain",
    "tear",
    "street",
    "lady",
    "less",
    "fear",
    "someone",
    "business",
    "able",
    "chair",
    "to forget",
    "to pick",
    "to expect",
    "red",
    "power",
    "to glance",
    "perhaps",
    "short",
    "ground",
    "true",
    "lip",
    "real",
    "to dress",
    "month",
    "to listen",
    "late",
    "school",
    "either",
    "whom",
    "low",
    "among",
    "husband",
    "to add",
    "different",
    "to drop",
    "to drink",
    "to learn",
    "suddenly",
    "paper",
    "land",
    "sort",
    "often",
    "evening",
    "above",
    "hundred",
    "to decide",
    "to notice",
    "daughter",
    "office",
    "cold",
    "figure",
    "road",
    "feeling",
    "to hang",
    "to cut",
    "number",
    "fine",
    "city",
    "to surprise",
    "to raise",
    "to fill",
    "several",
    "whose",
    "poor",
    "certain",
    "plan",
    "probably",
    "ago",
    "top",
    "to cause",
    "to enter",
    "ready",
    "blue",
    "within",
    "themselves",
    "forward",
    "sister",
    "to spend",
    "state",
    "however",
    "to fight",
    "strong",
    "to kiss",
    "during",
    "bit",
    "to please",
    "outside",
    "leg",
    "dear",
    "happy",
    "dream",
    "note",
    "wrong",
    "to realize",
    "interest",
    "blood",
    "quickly",
    "to explain",
    "wind",
    "human",
    "Lord",
    "to ride",
    "to cover",
    "to lean",
    "to allow",
    "ten",
    "doubt",
    "twenty",
    "sir",
    "beautiful",
    "war",
    "pretty",
    "slowly",
    "possible",
    "trouble",
    "to visit",
    "chance",
    "to push",
    "free",
    "breath",
    "piece",
    "sun",
    "truth",
    "to arrive",
    "to consider",
    "whether",
    "to act",
    "itself",
    "nor",
    "anyone",
    "sign",
    "deal",
    "to cross",
    "glass",
    "job",
    "to finish",
    "to whisper",
    "to study",
    "form",
    "easy",
    "age",
    "picture",
    "six",
    "finally",
    "to buy",
    "silence",
    "dog",
    "to lay",
    "sight",
    "ear",
    "to offer",
    "ship",
    "yourself",
    "towards",
    "sea",
    "ring",
    "to promise",
    "to lift",
    "to fly",
    "thousand",
    "to guess",
    "corner",
    "to worry",
    "view",
    "problem",
    "beside",
    "phone",
    "attention",
    "to hide",
    "to miss",
    "gaze",
    "police",
    "to save",
    "party",
    "English",
    "stone",
    "strange",
    "baby",
    "afraid",
    "pain",
    "wave",
    "kitchen",
    "to agree",
    "to strike",
    "to press",
    "green",
    "couple",
    "guy",
    "sorry",
    "experience",
    "till",
    "American",
    "maybe",
    "seat",
    "to roll",
    "indeed",
    "to blow",
    "sometimes",
    "heavy",
    "soul",
    "important",
    "kid",
    "to concern",
    "mine",
    "position",
    "hot",
    "doctor",
    "beyond",
    "to shout",
    "subject",
    "dinner",
    "to check",
    "spirit",
    "afternoon",
    "officer",
    "quiet",
    "desire",
    "except",
    "earth",
    "to imagine",
    "to pause",
    "to approach",
    "neck",
    "mile",
    "manner",
    "to join",
    "food",
    "building",
    "to stick",
    "edge",
    "field",
    "nature",
    "river",
    "rock",
    "gun",
    "to mention",
    "straight",
    "wide",
    "company",
    "sky",
    "to shoot",
    "wood",
    "to hit",
    "to dance",
    "crowd",
    "to burn",
    "fellow",
    "expression",
    "box",
    "control",
    "church",
    "to sigh",
    "everyone",
    "to choose",
    "to share",
    "to suggest",
    "king",
    "parent",
    "nice",
    "to slip",
    "to build",
    "onto",
    "nearly",
    "memory",
    "clothes",
    "report",
    "simply",
    "to accept",
    "to enjoy",
    "skin",
    "secret",
    "certainly",
    "game",
    "conversation",
    "boat",
    "empty",
    "today",
    "hell",
    "to serve",
    "soft",
    "to escape",
    "tone",
    "to hate",
    "direction",
    "attempt",
    "although",
    "group",
    "cheek",
    "pocket",
    "to manage",
    "yes",
    "to search",
    "to smell",
    "spring",
    "general",
    "middle",
    "account",
    "left",
    "exactly",
    "service",
    "following",
    "to hurt",
    "charge",
    "public",
    "to settle",
    "pleasure",
    "instead",
    "to discover",
    "gentleman",
    "gold",
    "whatever",
    "news",
    "knee",
    "bright",
    "immediately",
    "glad",
    "to beat",
    "fast",
    "single",
    "actually",
    "distance",
    "to receive",
    "spot",
    "scene",
    "to demand",
    "to admit",
    "train",
    "class",
    "animal",
    "desk",
    "hall",
    "chest",
    "master",
    "coffee",
    "to trust",
    "guard",
    "silent",
    "effect",
    "shadow",
    "to sing",
    "bag",
    "to prove",
    "French",
    "tall",
    "beneath",
    "to seek",
    "none",
    "to rush",
    "mountain",
    "to prepare",
    "soldier",
    "hardly",
    "bar",
    "to grin",
    "history",
    "clean",
    "to sell",
    "marriage",
    "action",
    "village",
    "member",
    "future",
    "hill",
    "especially",
    "garden",
    "sweet",
    "rain",
    "character",
    "to travel",
    "attack",
    "to shut",
    "smoke",
    "safe",
    "space",
    "area",
    "below",
    "situation",
    "to regard",
    "to refuse",
    "thirty",
    "dry",
    "to jump",
    "to repeat",
    "to lock",
    "art",
    "ahead",
    "third",
    "quick",
    "shirt",
    "to win",
    "nose",
    "summer",
    "throat",
    "effort",
    "simple",
    "term",
    "to teach",
    "race",
    "slow",
    "duty",
    "music",
    "Indian",
    "event",
    "flower",
    "to mark",
    "bird",
    "to gather",
    "Mr",
    "court",
    "meeting",
    "to scream",
    "hat",
    "to fail",
    "to climb",
    "murder",
    "to fit",
    "neither",
    "thin",
    "result",
    "to hurry",
    "complete",
    "tooth",
    "to tie",
    "purpose",
    "page",
    "thus",
    "suit",
    "enemy",
    "century",
    "to struggle",
    "usual",
    "object",
    "to wake",
    "rich",
    "to claim",
    "fair",
    "common",
    "strength",
    "thick",
    "stuff",
    "respect",
    "to address",
    "living",
    "seven",
    "to recognize",
    "to ought",
    "to support",
    "yard",
    "to grab",
    "brown",
    "command",
    "presence",
    "to describe",
    "coat",
    "station",
    "necessary",
    "to sink",
    "bank",
    "to stretch",
    "perfect",
    "to suffer",
    "sudden",
    "to disappear",
    "eight",
    "path",
    "particular",
    "to spread",
    "darkness",
    "stair",
    "to thank",
    "movement",
    "difficult",
    "shop",
    "pale",
    "to belong",
    "language",
    "special",
    "serious",
    "to remind",
    "to provide",
    "narrow",
    "condition",
    "to bend",
    "star",
    "bottle",
    "alive",
    "key",
    "to swing",
    "loud",
    "quietly",
    "mistake",
    "to observe",
    "to remark",
    "beauty",
    "carefully",
    "gate",
    "to knock",
    "to slide",
    "aware",
    "to remove",
    "completely",
    "to dare",
    "servant",
    "to bow",
    "circle",
    "record",
    "tea",
    "angry",
    "personal",
    "cloud",
    "rule",
    "battle",
    "board",
    "private",
    "wound",
    "natural",
    "somewhere",
    "forth",
    "taste",
    "to fix",
    "easily",
    "anyway",
    "creature",
    "length",
    "store",
    "fresh",
    "wine",
    "apartment",
    "occasion",
    "image",
    "system",
    "judge",
    "tongue",
    "pound",
    "cup",
    "to create",
    "shape",
    "worth",
    "song",
    "to produce",
    "tonight",
    "ill",
    "snow",
    "level",
    "fool",
    "therefore",
    "to count",
    "sick",
    "social",
    "tomorrow",
    "detail",
    "opinion",
    "to shrug",
    "to involve",
    "dollar",
    "huge",
    "to pour",
    "breast",
    "to tire",
    "slightly",
    "camp",
    "example",
    "trip",
    "hotel",
    "pair",
    "tale",
    "to flash",
    "likely",
    "usually",
    "impossible",
    "terrible",
    "society",
    "to steal",
    "peace",
    "message",
    "bedroom",
    "affair",
    "to occur",
    "to require",
    "shoe",
    "to intend",
    "heat",
    "color",
    "army",
    "stranger",
    "busy",
    "gray",
    "German",
    "to contain",
    "yellow",
    "card",
    "sharp",
    "to treat",
    "calm",
    "ball",
    "bottom",
    "danger",
    "entire",
    "to determine",
    "merely",
    "fish",
    "main",
    "to paint",
    "to cast",
    "author",
    "noise",
    "anger",
    "difference",
    "guest",
    "to suspect",
    "shock",
    "shot",
    "chief",
    "to shine",
    "to wash",
    "to breathe",
    "government",
    "to avoid",
    "stage",
    "fifty",
    "hole",
    "writer",
    "to burst",
    "choice",
    "silver",
    "to exclaim",
    "type",
    "tiny",
    "grass",
    "to direct",
    "appearance",
    "America",
    "wonderful",
    "to pack",
    "hospital",
    "hers",
    "gently",
    "softly",
    "track",
    "evidence",
    "evil",
    "to reveal",
    "to exist",
    "to drag",
    "to pray",
    "knowledge",
    "to express",
    "aside",
    "familiar",
    "god",
    "period",
    "block",
    "clearly",
    "to murmur",
    "post",
    "stream",
    "to sweep",
    "circumstance",
    "to insist",
    "quarter",
    "brain",
    "plain",
    "flat",
    "issue",
    "base",
    "delight",
    "island",
    "opportunity",
    "plant",
    "joy",
    "to shift",
    "relationship",
    "knife",
    "to brush",
    "slight",
    "damn",
    "to tremble",
    "to discuss",
    "various",
    "value",
    "park",
    "sex",
    "local",
    "youth",
    "practice",
    "wet",
    "breakfast",
    "captain",
    "to destroy",
    "journey",
    "Sunday",
    "somehow",
    "to frown",
    "to wrap",
    "cat",
    "bound",
    "comfort",
    "gesture",
    "priest",
    "France",
    "to handle",
    "heaven",
    "witness",
    "to increase",
    "feature",
    "to kick",
    "to assume",
    "asleep",
    "to recall",
    "match",
    "tight",
    "forest",
    "to protect",
    "lack",
    "companion",
    "entirely",
    "decision",
    "to include",
    "trail",
    "to invite",
    "emotion",
    "bone",
    "o'clock",
    "to surround",
    "final",
    "surface",
    "dozen",
    "to declare",
    "weapon",
    "center",
    "welcome",
    "crime",
    "weight",
    "lover",
    "sword",
    "list",
    "date",
    "to attend",
    "speech",
    "to assure",
    "to snap",
    "motion",
    "passion",
    "to advance",
    "sake",
    "influence",
    "unless",
    "speed",
    "folk",
    "storm",
    "moon",
    "to feed",
    "political",
    "to beg",
    "to accord",
    "machine",
    "forty",
    "nine",
    "to release",
    "north",
    "uncle",
    "ancient",
    "sad",
    "British",
    "faint",
    "double",
    "grave",
    "lunch",
    "instant",
    "plate",
    "to bury",
    "perfectly",
    "lovely",
    "yours",
    "ice",
    "to separate",
    "to bite",
    "roof",
    "to swear",
    "inch",
    "driver",
    "mirror",
    "stomach",
    "being",
    "to gain",
    "to ignore",
    "okay",
    "to respond",
    "nobody",
    "opposite",
    "to bother",
    "to arrange",
    "boot",
    "dust",
    "to rub",
    "directly",
    "glow",
    "to yell",
    "individual",
    "nurse",
    "Mrs",
    "vision",
    "to waste",
    "proud",
    "mad",
    "authority",
    "contact",
    "newspaper",
    "Christmas",
    "risk",
    "particularly",
    "degree",
    "former",
    "somewhat",
    "style",
    "somebody",
    "to possess",
    "truck",
    "interesting",
    "joke",
    "to mutter",
    "property",
    "bare",
    "flesh",
    "relief",
    "to hesitate",
    "to ease",
    "grip",
    "to leap",
    "supply",
    "to interrupt",
    "meal",
    "cousin",
    "process",
    "female",
    "loss",
    "cigarette",
    "iron",
    "to convince",
    "apart",
    "fancy",
    "row",
    "pace",
    "twice",
    "to flow",
    "patient",
    "to pretend",
    "size",
    "barely",
    "wedding",
    "to announce",
    "laughter",
    "sheet",
    "design",
    "to cook",
    "thy",
    "wheel",
    "success",
    "dangerous",
    "south",
    "awake",
    "loose",
    "forehead",
    "broad",
    "desert",
    "to stir",
    "stroke",
    "wing",
    "to warn",
    "to fold",
    "pile",
    "flame",
    "entrance",
    "lord",
    "to sail",
    "to introduce",
    "smooth",
    "powerful",
    "cost",
    "million",
    "faith",
    "to swallow",
    "bridge",
    "student",
    "measure",
    "everybody",
    "fortune",
    "due",
    "gentle",
    "to examine",
    "crazy",
    "fun",
    "pride",
    "male",
    "to engage",
    "test",
    "frame",
    "reality",
    "proper",
    "to reflect",
    "to wander",
    "to represent",
    "farm",
    "weather",
    "to satisfy",
    "difficulty",
    "weak",
    "meaning",
    "flight",
    "pleasant",
    "deck",
    "careful",
    "square",
    "excuse",
    "firm",
    "branch",
    "to wipe",
    "price",
    "twelve",
    "lawyer",
    "trace",
    "prayer",
    "anybody",
    "honor",
    "bell",
    "gift",
    "Christ",
    "energy",
    "possibly",
    "habit",
    "willing",
    "quality",
    "to toss",
    "fault",
    "to lower",
    "surely",
    "apparently",
    "to argue",
    "beginning",
    "handsome",
    "deeply",
    "to blame",
    "to protest",
    "prisoner",
    "to indicate",
    "thee",
    "to twist",
    "jacket",
    "hero",
    "luck",
    "content",
    "to inform",
    "to prevent",
    "happiness",
    "truly",
    "to develop",
    "chin",
    "to ruin",
    "to crack",
    "leader",
    "yesterday",
    "fifteen",
    "wooden",
    "to deliver",
    "material",
    "response",
    "passage",
    "stupid",
    "fashion",
    "task",
    "curious",
    "to succeed",
    "wise",
    "amount",
    "telephone",
    "to deny",
    "to dig",
    "law",
    "to urge",
    "forever",
    "community",
    "physical",
    "source",
    "palm",
    "teacher",
    "slave",
    "fat",
    "to prefer",
    "military",
    "bread",
    "to refer",
    "cabin",
    "fully",
    "unable",
    "to accompany",
    "to proceed",
    "to exchange",
    "mass",
    "request",
    "to establish",
    "odd",
    "shore",
    "to guide",
    "ourselves",
    "mere",
    "relation",
    "to threaten",
    "rate",
    "to curse",
    "beer",
    "distant",
    "obvious",
    "comment",
    "noble",
    "advantage",
    "spite",
    "file",
    "possibility",
    "to conduct",
    "to fade",
    "to focus",
    "screen",
    "existence",
    "to mount",
    "sand",
    "victim",
    "tip",
    "rage",
    "counter",
    "latter",
    "to scare",
    "accident",
    "impression",
    "to peer",
    "gay",
    "to curl",
    "to collect",
    "to march",
    "to display",
    "beach",
    "aunt",
    "doorway",
    "comfortable",
    "to drift",
    "pity",
    "excitement",
    "to arrest",
    "obviously",
    "otherwise",
    "trade",
    "club",
    "cell",
    "health",
    "leather",
    "rough",
    "to gasp",
    "to perform",
    "pink",
    "band",
    "sentence",
    "mood",
    "article",
    "chain",
    "carriage",
    "to utter",
    "shade",
    "plane",
    "college",
    "to forgive",
    "poem",
    "rope",
    "lamp",
    "instance",
    "pure",
    "to load",
    "to seize",
    "rear",
    "honest",
    "major",
    "similar",
    "activity",
    "to echo",
    "to occupy",
    "famous",
    "to survive",
    "anxious",
    "funny",
    "argument",
    "devil",
    "confidence",
    "to regret",
    "to commit",
    "sweat",
    "Russian",
    "range",
    "alarm",
    "to recover",
    "horror",
    "security",
    "crew",
    "to roar",
    "dawn",
    "nation",
    "metal",
    "nervous",
    "prison",
    "to abandon",
    "anywhere",
    "poet",
    "sin",
    "to grasp",
    "attitude",
    "to secure",
    "statement",
    "naked",
    "bill",
    "brow",
    "moral",
    "role",
    "plenty",
    "career",
    "tail",
    "birth",
    "to apply",
    "official",
    "to relate",
    "fate",
    "project",
    "valley",
    "imagination",
    "to frighten",
    "market",
    "fist",
    "to owe",
    "intention",
    "connection",
    "series",
    "courage",
    "tower",
    "lake",
    "to emerge",
    "to bet",
    "movie",
    "skirt",
    "to weep",
    "chamber",
    "trial",
    "magic",
    "engine",
    "thanks",
    "writing",
    "button",
    "film",
    "to hunt",
    "ordinary",
    "to extend",
    "to spare",
    "theory",
    "steady",
    "to grant",
    "June",
    "Jew",
    "text",
    "absolutely",
    "honour",
    "to float",
    "mystery",
    "season",
    "owner",
    "to afford",
    "colour",
    "advice",
    "partner",
    "to admire",
    "cap",
    "freedom",
    "to glare",
    "to deserve",
    "to greet",
    "to hug",
    "staff",
    "to thrust",
    "afterwards",
    "correct",
    "to depend",
    "to swim",
    "pool",
    "signal",
    "innocent",
    "heel",
    "generally",
    "curtain",
    "possession",
    "photograph",
    "scarcely",
    "radio",
    "native",
    "grey",
    "blanket",
    "interview",
    "to permit",
    "dirty",
    "shame",
    "to cease",
    "egg",
    "explanation",
    "wagon",
    "audience",
    "awful",
    "pipe",
    "to strain",
    "artist",
    "to squeeze",
    "to appeal",
    "cloth",
    "terror",
    "volume",
    "east",
    "section",
    "to disturb",
    "rank",
    "friendly",
    "hungry",
    "to creep",
    "visitor",
    "everywhere",
    "religious",
    "to obtain",
    "meat",
    "maid",
    "justice",
    "progress",
    "lap",
    "upstairs",
    "belief",
    "to connect",
    "novel",
    "ghost",
    "to aim",
    "to fling",
    "Saturday",
    "operation",
    "to relieve",
    "anymore",
    "despite",
    "waist",
    "milk",
    "to embrace",
    "bathroom",
    "pot",
    "to encounter",
    "estate",
    "previous",
    "to spin",
    "fiction",
    "grand",
    "trap",
    "to affect",
    "trick",
    "drug",
    "silk",
    "supper",
    "drunk",
    "hint",
    "to replace",
    "harm",
    "fruit",
    "computer",
    "elbow",
    "to descend",
    "to tap",
    "porch",
    "to swell",
    "upper",
    "cop",
    "grandfather",
    "exercise",
    "library",
    "muscle",
    "to freeze",
    "to upset",
    "to complain",
    "Europe",
    "favor",
    "root",
    "beast",
    "to arise",
    "challenge",
    "shower",
    "Greek",
    "throughout",
    "sexual",
    "string",
    "limit",
    "restaurant",
    "religion",
    "pressure",
    "to vanish",
    "grace",
    "vast",
    "to confess",
    "sacrifice",
    "arrival",
    "to jerk",
    "lesson",
    "lad",
    "oil",
    "pattern",
    "regular",
    "rifle",
    "lucky",
    "ass",
    "dull",
    "conscious",
    "mess",
    "element",
    "to groan",
    "consequence",
    "balance",
    "principle",
    "affection",
    "current",
    "candle",
    "shit",
    "to flee",
    "height",
    "stock",
    "knight",
    "clock",
    "castle",
    "fence",
    "guilty",
    "to resolve",
    "to kneel",
    "to relax",
    "temple",
    "besides",
    "magazine",
    "favorite",
    "seated",
    "tradition",
    "to appreciate",
    "science",
    "popular",
    "grandmother",
    "model",
    "to shiver",
    "daily",
    "discussion",
    "prince",
    "charm",
    "to strip",
    "to conclude",
    "uniform",
    "description",
    "ceiling",
    "bush",
    "FALSE",
    "interested",
    "closely",
    "to cling",
    "bench",
    "to pursue",
    "brave",
    "satisfaction",
    "to crawl",
    "bus",
    "literary",
    "bloody",
    "to compare",
    "foreign",
    "to propose",
    "pen",
    "to inquire",
    "grief",
    "aid",
    "friendship",
    "to crash",
    "adventure",
    "to stride",
    "culture",
    "beam",
    "safety",
    "March",
    "glasses",
    "ability",
    "excellent",
    "firmly",
    "understanding",
    "steel",
    "nerve",
    "angel",
    "giant",
    "suspicion",
    "unknown",
    "to startle",
    "equal",
    "tent",
    "to gleam",
    "smart",
    "generation",
    "to resist",
    "to sob",
    "per",
    "whenever",
    "spell",
    "reaction",
    "education",
    "proof",
    "to excite",
    "to blink",
    "to whip",
    "to identify",
    "bowl",
    "to expose",
    "warning",
    "depth",
    "chapter",
    "arrangement",
    "to ache",
    "to sip",
    "heavily",
    "Italian",
    "eyebrow",
    "to chuckle",
    "palace",
    "seriously",
    "to retreat",
    "painting",
    "importance",
    "queen",
    "silently",
    "wrist",
    "to slam",
    "responsibility",
    "altogether",
    "jaw",
    "badly",
    "passenger",
    "opening",
    "July",
    "skill",
    "mission",
    "to chase",
    "custom",
    "to tend",
    "method",
    "cow",
    "eager",
    "warrior",
    "to clutch",
    "to perceive",
    "cave",
    "credit",
    "praise",
    "capable",
    "to hire",
    "version",
    "neighbor",
    "to conceal",
    "to bore",
    "sympathy",
    "wire",
    "curiosity",
    "to oblige",
    "belt",
    "relative",
    "notion",
    "to capture",
    "to switch",
    "mail",
    "couch",
    "corridor",
    "to depart",
    "instantly",
    "Spanish",
    "threat",
    "Chinese",
    "highly",
    "eventually",
    "to employ",
    "link",
    "absence",
    "despair",
    "structure",
    "lonely",
    "grateful",
    "to withdraw",
    "map",
    "mostly",
    "minister",
    "pillow",
    "visible",
    "vessel",
    "mistress",
    "to attach",
    "delicate",
    "to confuse",
    "professional",
    "warmth",
    "broken",
    "to exhaust",
    "silly",
    "detective",
    "sorrow",
    "saddle",
    "damage",
    "rare",
    "to betray",
    "to slap",
    "to acknowledge",
    "gown",
    "solid",
    "extremely",
    "phrase",
    "nail",
    "to rent",
    "to maintain",
    "to impress",
    "worker",
    "bullet",
    "trunk",
    "conclusion",
    "pistol",
    "cottage",
    "brilliant",
    "citizen",
    "rapidly",
    "to whistle",
    "recently",
    "desperate",
    "lightly",
    "aspect",
    "confusion",
    "ugly",
    "intelligence",
    "sofa",
    "to shed",
    "darling",
    "dad",
    "curve",
    "breeze",
    "equally",
    "tape",
    "to venture",
    "to scratch",
    "scent",
    "to attract",
    "development",
    "to halt",
    "to pin",
    "to shove",
    "medical",
    "slope",
    "naturally",
    "mental",
    "to defend",
    "to earn",
    "to bid",
    "camera",
    "dirt",
    "shell",
    "plot",
    "crown",
    "successful",
    "virtue",
    "flood",
    "Rome",
    "purse",
    "poetry",
    "to pop",
    "belly",
    "total",
    "to confirm",
    "judgment",
    "enormous",
    "to crush",
    "basket",
    "shelter",
    "to pat",
    "responsible",
    "consciousness",
    "recent",
    "to divide",
    "criminal",
    "precious",
    "fairly",
    "to encourage",
    "border",
    "ocean",
    "blade",
    "thigh",
    "reflection",
    "funeral",
    "department",
    "unusual",
    "to persuade",
    "vehicle",
    "dread",
    "background",
    "standard",
    "television",
    "to accuse",
    "totally",
    "benefit",
    "dining",
    "to associate",
    "to render",
    "clerk",
    "permission",
    "coast",
    "mighty",
    "anxiety",
    "title",
    "tender",
    "research",
    "cake",
    "to rescue",
    "farmer",
    "violence",
    "glimpse",
    "suggestion",
    "childhood",
    "to suck",
    "foolish",
    "reward",
];

// ================================================================================================

export {
    myListVerbs,
    myListAdjs,
    someFrequentNouns,
    topicFamily,
    topicBody,
    topicGeo,
    someExpressions,
    topicAnimals,
    topicFoodDrinks,
    topicHome,
    topicClothes,
    topicDirections,
    topicTime,
    topicMaterials,
    topicNumbers,
    topicReligion,
    topicFrequency,
    topicUrgency,
    topicInformal,
    topicSwearWords,
    topicUnsorted,
    topicPrepositions,
    topicConjunctions,
    topicGlueWords,
    topicBasicPhrases,
};
