name: Build and Deploy

on:
    push:
        branches:
            - main # Run this workflow when pushing to the main branch
    workflow_dispatch: # Manually trigger the workflow

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # Checkout the repository code

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Set Node.js version

            - name: Install dependencies
              run: npm install # Install dependencies

            # Inject API Key and Build
            - name: Build the project
              env:
                  LINGVANEX_API_KEY: ${{ secrets.LINGVANEX_API_KEY }} # Inject the secret into the build process
              run: npm run build

            - name: Upload build artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist # Path to the built files

    deploy:
        needs: build # This step depends on the build job
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4 # Deploy to GitHub Pages
